-- =========================================================
-- ORDERS SYSTEM SCHEMA
-- Run this in Supabase SQL Editor to add order functionality
-- =========================================================

-- =========================================================
-- 1) ORDERS TABLE
-- =========================================================
CREATE TABLE IF NOT EXISTS public.orders (
  order_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Customer who placed the order
  customer_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  
  -- Pharmacy receiving the order
  pharmacy_id BIGINT NOT NULL REFERENCES public.pharmacies(pharmacy_id) ON DELETE CASCADE,
  
  -- Order status: pending -> confirmed -> ready -> completed / cancelled
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'confirmed', 'ready', 'completed', 'cancelled')),
  
  -- Order totals
  total_amount NUMERIC NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
  item_count INTEGER NOT NULL DEFAULT 0,
  
  -- Customer info snapshot (in case profile changes)
  customer_name TEXT,
  customer_phone TEXT,
  
  -- Notes
  customer_notes TEXT,
  pharmacy_notes TEXT,
  
  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
  confirmed_at TIMESTAMPTZ,
  ready_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  cancelled_at TIMESTAMPTZ
);

-- Indexes for common queries
CREATE INDEX IF NOT EXISTS idx_orders_customer ON public.orders(customer_id);
CREATE INDEX IF NOT EXISTS idx_orders_pharmacy ON public.orders(pharmacy_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON public.orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_created ON public.orders(created_at DESC);

-- updated_at trigger
DROP TRIGGER IF EXISTS trg_orders_updated ON public.orders;
CREATE TRIGGER trg_orders_updated
BEFORE UPDATE ON public.orders
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- =========================================================
-- 2) ORDER_ITEMS TABLE
-- =========================================================
CREATE TABLE IF NOT EXISTS public.order_items (
  item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  order_id BIGINT NOT NULL REFERENCES public.orders(order_id) ON DELETE CASCADE,
  medicine_id BIGINT NOT NULL REFERENCES public.medicines(medicine_id) ON DELETE CASCADE,
  
  -- Snapshot of medicine info at time of order
  medicine_name TEXT NOT NULL,
  medicine_form TEXT,
  medicine_strength TEXT,
  
  -- Quantity and pricing
  quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
  unit_price NUMERIC NOT NULL DEFAULT 0 CHECK (unit_price >= 0),
  subtotal NUMERIC NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
  
  created_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_order_items_order ON public.order_items(order_id);

-- =========================================================
-- 3) RLS POLICIES
-- =========================================================

-- Enable RLS
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

-- Orders: Customers can see their own orders
DROP POLICY IF EXISTS "Customers can view own orders" ON public.orders;
CREATE POLICY "Customers can view own orders" ON public.orders
  FOR SELECT USING (auth.uid() = customer_id);

-- Orders: Customers can create orders
DROP POLICY IF EXISTS "Customers can create orders" ON public.orders;
CREATE POLICY "Customers can create orders" ON public.orders
  FOR INSERT WITH CHECK (auth.uid() = customer_id);

-- Orders: Pharmacy owners can see orders for their pharmacy
DROP POLICY IF EXISTS "Owners can view pharmacy orders" ON public.orders;
CREATE POLICY "Owners can view pharmacy orders" ON public.orders
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.pharmacies 
      WHERE pharmacy_id = orders.pharmacy_id 
      AND owner_id = auth.uid()
    )
  );

-- Orders: Pharmacy owners can update order status
DROP POLICY IF EXISTS "Owners can update order status" ON public.orders;
CREATE POLICY "Owners can update order status" ON public.orders
  FOR UPDATE USING (
    EXISTS (
      SELECT 1 FROM public.pharmacies 
      WHERE pharmacy_id = orders.pharmacy_id 
      AND owner_id = auth.uid()
    )
  );

-- Order Items: Same visibility as parent order
DROP POLICY IF EXISTS "View order items via order access" ON public.order_items;
CREATE POLICY "View order items via order access" ON public.order_items
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.orders o
      WHERE o.order_id = order_items.order_id
      AND (o.customer_id = auth.uid() OR EXISTS (
        SELECT 1 FROM public.pharmacies p 
        WHERE p.pharmacy_id = o.pharmacy_id 
        AND p.owner_id = auth.uid()
      ))
    )
  );

-- Order Items: Customers can insert when creating order
DROP POLICY IF EXISTS "Customers can add order items" ON public.order_items;
CREATE POLICY "Customers can add order items" ON public.order_items
  FOR INSERT WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.orders o
      WHERE o.order_id = order_items.order_id
      AND o.customer_id = auth.uid()
    )
  );

-- =========================================================
-- 4) RPC FUNCTION: Place Order (atomic transaction)
-- =========================================================
CREATE OR REPLACE FUNCTION public.place_order(
  p_pharmacy_id BIGINT,
  p_items JSONB,  -- Array of {medicine_id, quantity, unit_price, medicine_name, medicine_form, medicine_strength}
  p_customer_name TEXT DEFAULT NULL,
  p_customer_phone TEXT DEFAULT NULL,
  p_customer_notes TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_order_id BIGINT;
  v_customer_id UUID;
  v_total NUMERIC := 0;
  v_item_count INTEGER := 0;
  v_item JSONB;
BEGIN
  -- Get current user
  v_customer_id := auth.uid();
  IF v_customer_id IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  -- Validate pharmacy exists
  IF NOT EXISTS (SELECT 1 FROM public.pharmacies WHERE pharmacy_id = p_pharmacy_id) THEN
    RAISE EXCEPTION 'Pharmacy not found';
  END IF;

  -- Calculate totals
  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    v_total := v_total + (COALESCE((v_item->>'unit_price')::NUMERIC, 0) * COALESCE((v_item->>'quantity')::INTEGER, 1));
    v_item_count := v_item_count + COALESCE((v_item->>'quantity')::INTEGER, 1);
  END LOOP;

  -- Create order
  INSERT INTO public.orders (
    customer_id,
    pharmacy_id,
    status,
    total_amount,
    item_count,
    customer_name,
    customer_phone,
    customer_notes
  ) VALUES (
    v_customer_id,
    p_pharmacy_id,
    'pending',
    v_total,
    v_item_count,
    p_customer_name,
    p_customer_phone,
    p_customer_notes
  )
  RETURNING order_id INTO v_order_id;

  -- Insert order items
  INSERT INTO public.order_items (
    order_id,
    medicine_id,
    medicine_name,
    medicine_form,
    medicine_strength,
    quantity,
    unit_price,
    subtotal
  )
  SELECT 
    v_order_id,
    (item->>'medicine_id')::BIGINT,
    item->>'medicine_name',
    item->>'medicine_form',
    item->>'medicine_strength',
    COALESCE((item->>'quantity')::INTEGER, 1),
    COALESCE((item->>'unit_price')::NUMERIC, 0),
    COALESCE((item->>'unit_price')::NUMERIC, 0) * COALESCE((item->>'quantity')::INTEGER, 1)
  FROM jsonb_array_elements(p_items) AS item;

  RETURN jsonb_build_object(
    'success', true,
    'order_id', v_order_id,
    'total_amount', v_total,
    'item_count', v_item_count
  );

EXCEPTION WHEN OTHERS THEN
  RETURN jsonb_build_object(
    'success', false,
    'error', SQLERRM
  );
END;
$$;

-- =========================================================
-- 5) RPC FUNCTION: Update Order Status
-- =========================================================
CREATE OR REPLACE FUNCTION public.update_order_status(
  p_order_id BIGINT,
  p_status TEXT,
  p_pharmacy_notes TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_owner_id UUID;
  v_pharmacy_id BIGINT;
BEGIN
  -- Get pharmacy_id and verify ownership
  SELECT o.pharmacy_id, p.owner_id 
  INTO v_pharmacy_id, v_owner_id
  FROM public.orders o
  JOIN public.pharmacies p ON p.pharmacy_id = o.pharmacy_id
  WHERE o.order_id = p_order_id;

  IF v_owner_id IS NULL OR v_owner_id != auth.uid() THEN
    RAISE EXCEPTION 'Not authorized to update this order';
  END IF;

  -- Update order status
  UPDATE public.orders
  SET 
    status = p_status,
    pharmacy_notes = COALESCE(p_pharmacy_notes, pharmacy_notes),
    confirmed_at = CASE WHEN p_status = 'confirmed' AND confirmed_at IS NULL THEN NOW() ELSE confirmed_at END,
    ready_at = CASE WHEN p_status = 'ready' AND ready_at IS NULL THEN NOW() ELSE ready_at END,
    completed_at = CASE WHEN p_status = 'completed' AND completed_at IS NULL THEN NOW() ELSE completed_at END,
    cancelled_at = CASE WHEN p_status = 'cancelled' AND cancelled_at IS NULL THEN NOW() ELSE cancelled_at END
  WHERE order_id = p_order_id;

  RETURN jsonb_build_object('success', true, 'status', p_status);

EXCEPTION WHEN OTHERS THEN
  RETURN jsonb_build_object('success', false, 'error', SQLERRM);
END;
$$;
