-- =========================================================
-- MEDISCAN: Complete Supabase Database Schema
-- Last Updated: February 2026
-- 
-- This file contains the full database schema for reference.
-- Run in Supabase SQL Editor to set up the database.
-- Idempotent (safe to re-run): uses IF NOT EXISTS + DROP IF EXISTS.
-- =========================================================

-- =========================================================
-- EXTENSIONS
-- =========================================================
create extension if not exists postgis;
create extension if not exists pg_trgm;

-- =========================================================
-- 1) MEDICINES (master list)
-- =========================================================
create table public.medicines (
  medicine_id bigint generated by default as identity primary key, 
  name text not null,          -- brand name
  generic_name text,           -- generic
  form text,                   -- dosage form
  strength text,               -- strength
  manufacturer text,           -- manufacturer
  price numeric,               -- Cleaned base price
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Helpful search indexes
create index if not exists idx_medicines_name on public.medicines(name);
create index if not exists idx_medicines_name_trgm
  on public.medicines using gin (name gin_trgm_ops);

-- =========================================================
-- 2) PROFILES (roles: customer vs pharmacy_owner)
-- =========================================================
create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'customer', -- customer | pharmacy_owner
  full_name text,
  phone text,
  preferences jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz default timezone('utc'::text, now()) not null
);

-- Add index for common preference queries
CREATE INDEX IF NOT EXISTS idx_profiles_preferences ON public.profiles USING gin (preferences);

-- Create profile automatically on signup (reads metadata for role, full_name, phone)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  user_role text;
  user_full_name text;
  user_phone text;
BEGIN
  -- Extract metadata from auth.users.raw_user_meta_data
  user_role := COALESCE(new.raw_user_meta_data->>'role', 'customer');
  user_full_name := new.raw_user_meta_data->>'full_name';
  user_phone := new.raw_user_meta_data->>'phone';
  
  -- Insert profile with role, full_name, phone from metadata
  INSERT INTO public.profiles (user_id, role, full_name, phone, preferences)
  VALUES (
    new.id,
    user_role,
    user_full_name,
    user_phone,
    '{}'::jsonb
  )
  ON CONFLICT (user_id) DO NOTHING;
  
  RETURN new;
END;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Prevent role changes after signup
CREATE OR REPLACE FUNCTION public.prevent_role_change()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF OLD.role IS DISTINCT FROM NEW.role THEN
    RAISE EXCEPTION 'Role cannot be changed after signup. Current role: %', OLD.role;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_prevent_role_change ON public.profiles;
CREATE TRIGGER trg_prevent_role_change
BEFORE UPDATE ON public.profiles
FOR EACH ROW
EXECUTE FUNCTION public.prevent_role_change();

-- =========================================================
-- 3) PHARMACIES (single owner per pharmacy + PostGIS location)
-- =========================================================
create table if not exists public.pharmacies (
  pharmacy_id bigint generated by default as identity primary key,
  owner_id uuid references auth.users(id) on delete set null,

  name text not null,
  address text,

  latitude double precision,
  longitude double precision,

  -- PostGIS best-practice column for geo search
  location geography(point, 4326),

  contact_number text,
  email text,
  opening_hours text,

  created_at timestamptz default timezone('utc'::text, now()) not null
);

-- Keep location updated automatically from lat/lng
create or replace function public.set_pharmacy_location()
returns trigger
language plpgsql
as $$
begin
  if new.longitude is not null and new.latitude is not null then
    new.location := st_setsrid(st_makepoint(new.longitude, new.latitude), 4326)::geography;
  else
    new.location := null;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_set_pharmacy_location on public.pharmacies;
create trigger trg_set_pharmacy_location
before insert or update of latitude, longitude
on public.pharmacies
for each row execute function public.set_pharmacy_location();

-- Indexes
create index if not exists idx_pharmacies_owner on public.pharmacies(owner_id);
create index if not exists idx_pharmacies_location_latlng on public.pharmacies(latitude, longitude);
create index if not exists pharmacies_location_gix on public.pharmacies using gist (location);

-- =========================================================
-- 4) PHARMACY_MEDICINES (inventory join table)
-- =========================================================
create table if not exists public.pharmacy_medicines (
  id bigint generated by default as identity primary key,

  pharmacy_id bigint not null references public.pharmacies(pharmacy_id) on delete cascade,
  medicine_id bigint not null references public.medicines(medicine_id) on delete cascade,

  -- pharmacy-specific override price (nullable -> fallback to medicines.price)
  price numeric check (price is null or price >= 0),

  stock_qty integer not null default 0 check (stock_qty >= 0),
  is_available boolean not null default true,

  -- Pack configuration
  leaflets_per_box integer DEFAULT 1 CHECK (leaflets_per_box > 0),
  pills_per_leaflet integer DEFAULT 1 CHECK (pills_per_leaflet > 0),
  
  -- Unit type and size
  unit_type text not null default 'pill'
    check (unit_type in ('pill','bottle','vial','tube','sachet','piece','ml')),
  unit_size_text text,
  
  -- Reorder and active batch
  reorder_level integer not null default 0 check (reorder_level >= 0),
  active_batch_id bigint,

  created_at timestamptz default timezone('utc'::text, now()) not null,
  updated_at timestamptz default timezone('utc'::text, now()) not null,

  unique (pharmacy_id, medicine_id)
);

create index if not exists idx_pharmacy_medicines_lookup
  on public.pharmacy_medicines(pharmacy_id, medicine_id);

create index if not exists idx_pharmacy_medicines_medicine
  on public.pharmacy_medicines(medicine_id);

-- updated_at trigger
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$;

drop trigger if exists trg_pharmacy_medicines_updated on public.pharmacy_medicines;
create trigger trg_pharmacy_medicines_updated
before update on public.pharmacy_medicines
for each row execute function public.set_updated_at();

-- =========================================================
-- 5) PHARMACY_MEDICINE_BATCHES (batch tracking with expiry)
-- =========================================================
create table if not exists public.pharmacy_medicine_batches (
  batch_id bigint generated by default as identity primary key,
  pharmacy_medicine_id bigint not null references public.pharmacy_medicines(id) on delete cascade,
  batch_no text,
  expiry_date date not null,
  buy_price numeric check (buy_price is null or buy_price >= 0),
  qty_remaining integer not null default 0 check (qty_remaining >= 0),
  created_at timestamptz default timezone('utc'::text, now()) not null
);

create index if not exists idx_batches_pm_expiry
  on public.pharmacy_medicine_batches (pharmacy_medicine_id, expiry_date);

-- FK for active batch
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'fk_pm_active_batch'
  ) then
    alter table public.pharmacy_medicines
      add constraint fk_pm_active_batch
      foreign key (active_batch_id)
      references public.pharmacy_medicine_batches(batch_id)
      on delete set null;
  end if;
end $$;

-- Sync stock_qty from batches
create or replace function public.sync_pharmacy_stock_qty()
returns trigger
language plpgsql
as $$
declare
  pm_id bigint;
begin
  pm_id := coalesce(new.pharmacy_medicine_id, old.pharmacy_medicine_id);

  update public.pharmacy_medicines pm
  set stock_qty = (
    select coalesce(sum(b.qty_remaining), 0)
    from public.pharmacy_medicine_batches b
    where b.pharmacy_medicine_id = pm_id
  )
  where pm.id = pm_id;

  return null;
end;
$$;

drop trigger if exists trg_sync_stock_qty_ins on public.pharmacy_medicine_batches;
drop trigger if exists trg_sync_stock_qty_upd on public.pharmacy_medicine_batches;
drop trigger if exists trg_sync_stock_qty_del on public.pharmacy_medicine_batches;

create trigger trg_sync_stock_qty_ins
after insert on public.pharmacy_medicine_batches
for each row execute function public.sync_pharmacy_stock_qty();

create trigger trg_sync_stock_qty_upd
after update on public.pharmacy_medicine_batches
for each row execute function public.sync_pharmacy_stock_qty();

create trigger trg_sync_stock_qty_del
after delete on public.pharmacy_medicine_batches
for each row execute function public.sync_pharmacy_stock_qty();

-- =========================================================
-- 6) INVENTORY LEDGER (audit trail)
-- =========================================================
create table if not exists public.inventory_ledger (
  entry_id bigint generated by default as identity primary key,
  pharmacy_id bigint not null references public.pharmacies(pharmacy_id) on delete cascade,
  pharmacy_medicine_id bigint not null references public.pharmacy_medicines(id) on delete cascade,
  entry_type text not null check (entry_type in ('stock_in','stock_out','adjustment','move')),
  qty_base_units integer not null,
  note text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz default timezone('utc'::text, now()) not null
);

create index if not exists idx_ledger_pm_created
  on public.inventory_ledger (pharmacy_medicine_id, created_at desc);

create table if not exists public.inventory_ledger_allocations (
  allocation_id bigint generated by default as identity primary key,
  entry_id bigint not null references public.inventory_ledger(entry_id) on delete cascade,
  batch_id bigint references public.pharmacy_medicine_batches(batch_id) on delete set null,
  qty_base_units integer not null
);

create index if not exists idx_ledger_alloc_entry
  on public.inventory_ledger_allocations(entry_id);

-- =========================================================
-- 7) PHARMACY_UNIT_CONVERSIONS (multi-pack conversions)
-- =========================================================
create table if not exists public.pharmacy_unit_conversions (
  conversion_id bigint generated by default as identity primary key,
  pharmacy_medicine_id bigint not null references public.pharmacy_medicines(id) on delete cascade,
  unit_label text not null,
  multiplier_to_base integer not null check (multiplier_to_base > 0),
  is_default boolean not null default false,
  created_at timestamptz default timezone('utc'::text, now()) not null,
  unique (pharmacy_medicine_id, unit_label, multiplier_to_base)
);

create index if not exists idx_conv_pm on public.pharmacy_unit_conversions(pharmacy_medicine_id);

-- Sync default pill conversions from legacy columns
create or replace function public.sync_default_pill_conversions()
returns trigger
language plpgsql
as $$
declare
  v_pills int;
  v_leaflets int;
  v_box_mult int;
begin
  -- Only meaningful for pill-based meds
  if new.unit_type <> 'pill' then
    return new;
  end if;

  v_pills := greatest(coalesce(new.pills_per_leaflet, 1), 1);
  v_leaflets := greatest(coalesce(new.leaflets_per_box, 1), 1);
  v_box_mult := v_pills * v_leaflets;

  -- Ensure base unit exists
  insert into public.pharmacy_unit_conversions(pharmacy_medicine_id, unit_label, multiplier_to_base, is_default)
  values (new.id, 'pill', 1, true)
  on conflict (pharmacy_medicine_id, unit_label, multiplier_to_base) do update
    set is_default = true;

  -- Default leaflet
  insert into public.pharmacy_unit_conversions(pharmacy_medicine_id, unit_label, multiplier_to_base, is_default)
  values (new.id, 'leaflet', v_pills, true)
  on conflict (pharmacy_medicine_id, unit_label, multiplier_to_base) do update
    set is_default = true;

  -- Default box
  insert into public.pharmacy_unit_conversions(pharmacy_medicine_id, unit_label, multiplier_to_base, is_default)
  values (new.id, 'box', v_box_mult, true)
  on conflict (pharmacy_medicine_id, unit_label, multiplier_to_base) do update
    set is_default = true;

  return new;
end;
$$;

drop trigger if exists trg_sync_default_pill_conversions on public.pharmacy_medicines;
create trigger trg_sync_default_pill_conversions
after insert or update of pills_per_leaflet, leaflets_per_box, unit_type
on public.pharmacy_medicines
for each row execute function public.sync_default_pill_conversions();

-- =========================================================
-- 8) ROW LEVEL SECURITY (RLS) + POLICIES
-- =========================================================
alter table public.medicines enable row level security;
alter table public.profiles enable row level security;
alter table public.pharmacies enable row level security;
alter table public.pharmacy_medicines enable row level security;
alter table public.pharmacy_medicine_batches enable row level security;
alter table public.inventory_ledger enable row level security;
alter table public.inventory_ledger_allocations enable row level security;
alter table public.pharmacy_unit_conversions enable row level security;

-- ---------- Public read (customer side needs this) ----------
drop policy if exists "Public read medicines" on public.medicines;
create policy "Public read medicines"
on public.medicines for select
using (true);

drop policy if exists "Public read pharmacies" on public.pharmacies;
create policy "Public read pharmacies"
on public.pharmacies for select
using (true);

drop policy if exists "Public read inventory" on public.pharmacy_medicines;
create policy "Public read inventory"
on public.pharmacy_medicines for select
using (true);

-- ---------- Profiles ----------
drop policy if exists "Users read own profile" on public.profiles;
create policy "Users read own profile"
on public.profiles for select
using (user_id = auth.uid());

drop policy if exists "Users insert own profile" on public.profiles;
create policy "Users insert own profile"
on public.profiles for insert
with check (user_id = auth.uid());

drop policy if exists "Users update own profile" on public.profiles;
CREATE POLICY "Users update own profile"
ON public.profiles FOR UPDATE
USING (user_id = auth.uid())
WITH CHECK (
  user_id = auth.uid()
  AND (
    role = (SELECT role FROM public.profiles WHERE user_id = auth.uid())
  )
);

-- ---------- Pharmacies ----------
drop policy if exists "Pharmacy owners can insert pharmacy" on public.pharmacies;
create policy "Pharmacy owners can insert pharmacy"
on public.pharmacies for insert
with check (
  owner_id = auth.uid()
  and exists (
    select 1 from public.profiles pr
    where pr.user_id = auth.uid()
      and pr.role = 'pharmacy_owner'
  )
);

drop policy if exists "Owners update own pharmacy" on public.pharmacies;
create policy "Owners update own pharmacy"
on public.pharmacies for update
using (owner_id = auth.uid())
with check (owner_id = auth.uid());

drop policy if exists "Owners delete own pharmacy" on public.pharmacies;
create policy "Owners delete own pharmacy"
on public.pharmacies for delete
using (owner_id = auth.uid());

-- ---------- Pharmacy Medicines (Inventory) ----------
drop policy if exists "Owners insert inventory" on public.pharmacy_medicines;
create policy "Owners insert inventory"
on public.pharmacy_medicines for insert
with check (
  exists (
    select 1 from public.pharmacies p
    where p.pharmacy_id = pharmacy_medicines.pharmacy_id
      and p.owner_id = auth.uid()
  )
);

drop policy if exists "Owners update inventory" on public.pharmacy_medicines;
create policy "Owners update inventory"
on public.pharmacy_medicines for update
using (
  exists (
    select 1 from public.pharmacies p
    where p.pharmacy_id = pharmacy_medicines.pharmacy_id
      and p.owner_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.pharmacies p
    where p.pharmacy_id = pharmacy_medicines.pharmacy_id
      and p.owner_id = auth.uid()
  )
);

drop policy if exists "Owners delete inventory" on public.pharmacy_medicines;
create policy "Owners delete inventory"
on public.pharmacy_medicines for delete
using (
  exists (
    select 1 from public.pharmacies p
    where p.pharmacy_id = pharmacy_medicines.pharmacy_id
      and p.owner_id = auth.uid()
  )
);

-- ---------- Batches (owner-only) ----------
drop policy if exists "Owners manage batches" on public.pharmacy_medicine_batches;
create policy "Owners manage batches"
on public.pharmacy_medicine_batches
for all
using (
  exists (
    select 1
    from public.pharmacy_medicines pm
    join public.pharmacies p on p.pharmacy_id = pm.pharmacy_id
    where pm.id = pharmacy_medicine_batches.pharmacy_medicine_id
      and p.owner_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.pharmacy_medicines pm
    join public.pharmacies p on p.pharmacy_id = pm.pharmacy_id
    where pm.id = pharmacy_medicine_batches.pharmacy_medicine_id
      and p.owner_id = auth.uid()
  )
);

-- ---------- Ledger (owner-only) ----------
drop policy if exists "Owners read/write ledger" on public.inventory_ledger;
create policy "Owners read/write ledger"
on public.inventory_ledger
for all
using (
  exists (
    select 1 from public.pharmacies p
    where p.pharmacy_id = inventory_ledger.pharmacy_id
      and p.owner_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.pharmacies p
    where p.pharmacy_id = inventory_ledger.pharmacy_id
      and p.owner_id = auth.uid()
  )
);

drop policy if exists "Owners read/write allocations" on public.inventory_ledger_allocations;
create policy "Owners read/write allocations"
on public.inventory_ledger_allocations
for all
using (
  exists (
    select 1
    from public.inventory_ledger l
    join public.pharmacies p on p.pharmacy_id = l.pharmacy_id
    where l.entry_id = inventory_ledger_allocations.entry_id
      and p.owner_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.inventory_ledger l
    join public.pharmacies p on p.pharmacy_id = l.pharmacy_id
    where l.entry_id = inventory_ledger_allocations.entry_id
      and p.owner_id = auth.uid()
  )
);

-- ---------- Unit Conversions (owner-only) ----------
drop policy if exists "Owners manage conversions" on public.pharmacy_unit_conversions;
create policy "Owners manage conversions"
on public.pharmacy_unit_conversions
for all
using (
  exists (
    select 1
    from public.pharmacy_medicines pm
    join public.pharmacies p on p.pharmacy_id = pm.pharmacy_id
    where pm.id = pharmacy_unit_conversions.pharmacy_medicine_id
      and p.owner_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.pharmacy_medicines pm
    join public.pharmacies p on p.pharmacy_id = pm.pharmacy_id
    where pm.id = pharmacy_unit_conversions.pharmacy_medicine_id
      and p.owner_id = auth.uid()
  )
);

-- =========================================================
-- 9) VIEWS
-- =========================================================

-- Expiring batches view
create or replace view public.v_pharmacy_expiring_batches as
select
  pm.pharmacy_id,
  pm.id as pharmacy_medicine_id,
  pm.medicine_id,
  m.name as brand_name,
  m.generic_name,
  pm.unit_type,
  b.batch_id,
  b.batch_no,
  b.expiry_date,
  b.qty_remaining
from public.pharmacy_medicine_batches b
join public.pharmacy_medicines pm on pm.id = b.pharmacy_medicine_id
join public.medicines m on m.medicine_id = pm.medicine_id
where b.qty_remaining > 0;

-- Inventory summary view
DROP VIEW IF EXISTS public.v_pharmacy_inventory_summary;
CREATE OR REPLACE VIEW public.v_pharmacy_inventory_summary AS
SELECT 
  p.pharmacy_id,
  pm.id AS pharmacy_medicine_id,
  m.medicine_id,
  m.name AS medicine_name,
  m.form,
  m.strength,
  pm.unit_type,
  pm.stock_qty AS total_base_units,
  pm.reorder_level,
  pm.is_available,
  pm.pills_per_leaflet,
  pm.leaflets_per_box,
  MIN(b.expiry_date) FILTER (WHERE b.qty_remaining > 0) AS next_expiry_date,
  COUNT(b.batch_id) FILTER (WHERE b.qty_remaining > 0) AS active_batch_count,
  COALESCE(SUM(b.qty_remaining) FILTER (WHERE b.expiry_date < CURRENT_DATE), 0) AS expired_qty
FROM public.pharmacies p
JOIN public.pharmacy_medicines pm ON pm.pharmacy_id = p.pharmacy_id
JOIN public.medicines m ON m.medicine_id = pm.medicine_id
LEFT JOIN public.pharmacy_medicine_batches b ON b.pharmacy_medicine_id = pm.id
GROUP BY p.pharmacy_id, pm.id, m.medicine_id, m.name, m.form, m.strength, 
         pm.unit_type, pm.stock_qty, pm.reorder_level, pm.is_available,
         pm.pills_per_leaflet, pm.leaflets_per_box;

ALTER VIEW public.v_pharmacy_inventory_summary SET (security_invoker = true);

-- =========================================================
-- 10) RPC FUNCTIONS
-- =========================================================

-- Find best pharmacies near user
create or replace function public.find_best_pharmacies(
  user_lat double precision,
  user_lng double precision,
  medicine_ids bigint[],
  radius_m integer default 5000
)
returns table (
  pharmacy_id bigint,
  name text,
  address text,
  latitude double precision,
  longitude double precision,
  matched_items integer,
  total_price numeric,
  distance_m double precision
)
language sql
stable
as $$
  select
    p.pharmacy_id,
    p.name,
    p.address,
    p.latitude,
    p.longitude,
    count(distinct pm.medicine_id)::int as matched_items,
    sum(coalesce(pm.price, m.price)) as total_price,
    st_distance(p.location, st_point(user_lng, user_lat)::geography) as distance_m
  from public.pharmacies p
  join public.pharmacy_medicines pm on pm.pharmacy_id = p.pharmacy_id
  join public.medicines m on m.medicine_id = pm.medicine_id
  where pm.medicine_id = any(medicine_ids)
    and pm.is_available = true
    and pm.stock_qty > 0
    and p.location is not null
    and st_dwithin(p.location, st_point(user_lng, user_lat)::geography, radius_m)
  group by p.pharmacy_id, p.name, p.address, p.latitude, p.longitude, p.location
  order by matched_items desc, total_price asc, distance_m asc;
$$;

-- Stock In (creates/merges batches + writes ledger)
CREATE OR REPLACE FUNCTION public.inventory_stock_in(
  p_pharmacy_medicine_id bigint,
  p_qty_base_units integer,
  p_expiry_date date,
  p_batch_no text default null,
  p_buy_price numeric default null,
  p_note text default null
)
returns bigint
language plpgsql
as $$
declare
  v_batch_id bigint;
  v_pharmacy_id bigint;
  v_entry_id bigint;
begin
  if p_qty_base_units is null or p_qty_base_units <= 0 then
    raise exception 'qty_base_units must be > 0';
  end if;
  if p_expiry_date is null then
    raise exception 'expiry_date is required';
  end if;
  select pm.pharmacy_id into v_pharmacy_id
  from public.pharmacy_medicines pm
  join public.pharmacies p on p.pharmacy_id = pm.pharmacy_id
  where pm.id = p_pharmacy_medicine_id
    and p.owner_id = auth.uid();
  if v_pharmacy_id is null then
    raise exception 'not allowed';
  end if;
  -- merge if batch_no + expiry matches
  if p_batch_no is not null and length(trim(p_batch_no)) > 0 then
    select b.batch_id
      into v_batch_id
    from public.pharmacy_medicine_batches b
    where b.pharmacy_medicine_id = p_pharmacy_medicine_id
      and b.batch_no = p_batch_no
      and b.expiry_date = p_expiry_date
    limit 1;
    if v_batch_id is not null then
      update public.pharmacy_medicine_batches
      set qty_remaining = qty_remaining + p_qty_base_units,
          buy_price = coalesce(p_buy_price, buy_price)
      where batch_id = v_batch_id;
    end if;
  end if;
  if v_batch_id is null then
    insert into public.pharmacy_medicine_batches(
      pharmacy_medicine_id, batch_no, expiry_date, buy_price, qty_remaining
    )
    values (
      p_pharmacy_medicine_id,
      nullif(trim(p_batch_no), ''),
      p_expiry_date,
      p_buy_price,
      p_qty_base_units
    )
    returning batch_id into v_batch_id;
  end if;
  insert into public.inventory_ledger(pharmacy_id, pharmacy_medicine_id, entry_type, qty_base_units, note, created_by)
  values (v_pharmacy_id, p_pharmacy_medicine_id, 'stock_in', p_qty_base_units, p_note, auth.uid())
  returning entry_id into v_entry_id;
  insert into public.inventory_ledger_allocations(entry_id, batch_id, qty_base_units)
  values (v_entry_id, v_batch_id, p_qty_base_units);
  return v_batch_id;
end;
$$;

-- Stock Out (FEFO + active batch priority + writes ledger)
CREATE OR REPLACE FUNCTION public.inventory_stock_out(
  p_pharmacy_medicine_id bigint,
  p_qty_base_units integer,
  p_preferred_batch_id bigint default null,
  p_use_active_batch boolean default true,
  p_note text default null
)
returns jsonb
language plpgsql
as $$
declare
  v_remaining integer := p_qty_base_units;
  v_alloc jsonb := '[]'::jsonb;
  v_take integer;
  v_active_batch_id bigint;
  v_pharmacy_id bigint;
  v_entry_id bigint;
  r record;
begin
  if p_qty_base_units is null or p_qty_base_units <= 0 then
    raise exception 'qty_base_units must be > 0';
  end if;
  select pm.pharmacy_id into v_pharmacy_id
  from public.pharmacy_medicines pm
  join public.pharmacies p on p.pharmacy_id = pm.pharmacy_id
  where pm.id = p_pharmacy_medicine_id
    and p.owner_id = auth.uid();
  if v_pharmacy_id is null then
    raise exception 'not allowed';
  end if;
  select active_batch_id into v_active_batch_id
  from public.pharmacy_medicines
  where id = p_pharmacy_medicine_id;
  insert into public.inventory_ledger(pharmacy_id, pharmacy_medicine_id, entry_type, qty_base_units, note, created_by)
  values (v_pharmacy_id, p_pharmacy_medicine_id, 'stock_out', -p_qty_base_units, p_note, auth.uid())
  returning entry_id into v_entry_id;
  for r in
    select
      b.batch_id,
      b.expiry_date,
      b.qty_remaining
    from public.pharmacy_medicine_batches b
    where b.pharmacy_medicine_id = p_pharmacy_medicine_id
      and b.qty_remaining > 0
      and b.expiry_date >= current_date
    order by
      case when b.batch_id = p_preferred_batch_id then 0 else 1 end,
      case when p_use_active_batch and b.batch_id = v_active_batch_id then 0 else 1 end,
      b.expiry_date asc,
      b.batch_id asc
    for update
  loop
    exit when v_remaining = 0;
    v_take := least(v_remaining, r.qty_remaining);
    update public.pharmacy_medicine_batches
    set qty_remaining = qty_remaining - v_take
    where batch_id = r.batch_id;
    insert into public.inventory_ledger_allocations(entry_id, batch_id, qty_base_units)
    values (v_entry_id, r.batch_id, -v_take);
    v_alloc := v_alloc || jsonb_build_object(
      'batch_id', r.batch_id,
      'take', v_take,
      'expiry_date', r.expiry_date
    );
    v_remaining := v_remaining - v_take;
  end loop;
  if v_remaining > 0 then
    raise exception 'insufficient stock: missing % base units', v_remaining;
  end if;
  return v_alloc;
end;
$$;

-- Move stock between batches (correction tool)
create or replace function public.inventory_move_between_batches(
  p_from_batch_id bigint,
  p_to_batch_id bigint,
  p_qty_base_units integer
)
returns void
language plpgsql
as $$
declare
  v_pm_from bigint;
  v_pm_to bigint;
begin
  if p_qty_base_units is null or p_qty_base_units <= 0 then
    raise exception 'qty_base_units must be > 0';
  end if;

  select pharmacy_medicine_id into v_pm_from
  from public.pharmacy_medicine_batches
  where batch_id = p_from_batch_id
  for update;

  select pharmacy_medicine_id into v_pm_to
  from public.pharmacy_medicine_batches
  where batch_id = p_to_batch_id
  for update;

  if v_pm_from is null or v_pm_to is null then
    raise exception 'batch not found';
  end if;

  if v_pm_from <> v_pm_to then
    raise exception 'batches must belong to same pharmacy_medicine_id';
  end if;

  -- auth check owner
  if not exists (
    select 1
    from public.pharmacy_medicines pm
    join public.pharmacies p on p.pharmacy_id = pm.pharmacy_id
    where pm.id = v_pm_from
      and p.owner_id = auth.uid()
  ) then
    raise exception 'not allowed';
  end if;

  update public.pharmacy_medicine_batches
  set qty_remaining = qty_remaining - p_qty_base_units
  where batch_id = p_from_batch_id
    and qty_remaining >= p_qty_base_units;

  if not found then
    raise exception 'insufficient stock in from-batch';
  end if;

  update public.pharmacy_medicine_batches
  set qty_remaining = qty_remaining + p_qty_base_units
  where batch_id = p_to_batch_id;
end;
$$;

-- =========================================================
-- END OF SCHEMA
-- =========================================================
